### ISSUE TITLE
Please add a LICENSE to this repository.

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/potools#2]
Typically Mozilla folks use MPL2, but I defer to whatever considerations are appropriate for this public repository.

**Comment by muffinresearch** [comment]
It is MPL2 as per the package.json [1] but I will add an explicit file. Thanks for the report!

[1] https://github.com/mozilla/potools/blob/945842eae066f1d1583cbb2cbc384396c56f8e7f/package.json#L23
